version: '3'
services:
  app:
    build: ./
    image: wechat-spider:latest
    restart: always
    environment:
      - NODE_ENV=production
      - DEPLOY=docker
    expose:
      - "8101"
      - "8104"
    ports:
      - 8101:8101
      - 8104:8104
    links:
      - redis
      - mongo
  redis:
    image: redis:latest
    restart: always
  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - "${MONGO_PATH}:/data/db"
